DROP TABLE IF EXISTS webcams, comments, dreamField, blackList;

CREATE TABLE webcams (
  id INTEGER PRIMARY KEY,
  title VARCHAR(255),
  likes INTEGER DEFAULT 0
);

INSERT INTO webcams (id, title, likes) VALUES(0, 'random', 0);

CREATE TABLE comments(
  id SERIAL PRIMARY KEY,
  video_id INTEGER NOT NULL REFERENCES webcams(id),
  text VARCHAR(200),
  handle VARCHAR(20),
  timeStamp BIGINT
);

CREATE TABLE dreamField(
  id INTEGER NOT NULL REFERENCES comments(id)
);

CREATE TABLE blackList(
  video_id INTEGER NOT NULL REFERENCES webcams(id)
);

INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Lorem', 'Anonymous', 0); INSERT INTO dreamField (id) VALUES(0);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'ipsum', 'Anonymous', 1); INSERT INTO dreamField (id) VALUES(1);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Mel', 'Anonymous', 2); INSERT INTO dreamField (id) VALUES(2);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Fisher', 'Anonymous', 3); INSERT INTO dreamField (id) VALUES(3);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'florida', 'Anonymous', 4); INSERT INTO dreamField (id) VALUES(4);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'straights', 'Anonymous', 5); INSERT INTO dreamField (id) VALUES(5);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'coast', 'Anonymous', 6); INSERT INTO dreamField (id) VALUES(6);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'guard', 'Anonymous', 7); INSERT INTO dreamField (id) VALUES(7);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'civil', 'Anonymous', 8); INSERT INTO dreamField (id) VALUES(8);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'war', 'Anonymous', 9); INSERT INTO dreamField (id) VALUES(9);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'palm', 'Anonymous', 10); INSERT INTO dreamField (id) VALUES(10);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'tree', 'Anonymous', 11); INSERT INTO dreamField (id) VALUES(11);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'dive', 'Anonymous', 12); INSERT INTO dreamField (id) VALUES(12);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Captain', 'Anonymous', 13); INSERT INTO dreamField (id) VALUES(13);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Eric', 'Anonymous', 14); INSERT INTO dreamField (id) VALUES(14);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'reef', 'Anonymous', 15); INSERT INTO dreamField (id) VALUES(15);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'sailfish', 'Anonymous', 16); INSERT INTO dreamField (id) VALUES(16);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'boat', 'Anonymous', 17); INSERT INTO dreamField (id) VALUES(17);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'starboard', 'Anonymous', 18); INSERT INTO dreamField (id) VALUES(18);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'sailing', 'Anonymous', 19); INSERT INTO dreamField (id) VALUES(19);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Over-Sea', 'Anonymous', 20); INSERT INTO dreamField (id) VALUES(20);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Railroad', 'Anonymous', 21); INSERT INTO dreamField (id) VALUES(21);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'stock', 'Anonymous', 22); INSERT INTO dreamField (id) VALUES(22);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'island', 'Anonymous', 23); INSERT INTO dreamField (id) VALUES(23);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'boca', 'Anonymous', 24); INSERT INTO dreamField (id) VALUES(24);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'grand', 'Anonymous', 25); INSERT INTO dreamField (id) VALUES(25);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Truman', 'Anonymous', 26); INSERT INTO dreamField (id) VALUES(26);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Annex', 'Anonymous', 27); INSERT INTO dreamField (id) VALUES(27);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Harry', 'Anonymous', 28); INSERT INTO dreamField (id) VALUES(28);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Truman', 'Anonymous', 29); INSERT INTO dreamField (id) VALUES(29);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'one', 'Anonymous', 30); INSERT INTO dreamField (id) VALUES(30);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'human', 'Anonymous', 31); INSERT INTO dreamField (id) VALUES(31);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'family', 'Anonymous', 32); INSERT INTO dreamField (id) VALUES(32);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'mallory', 'Anonymous', 33); INSERT INTO dreamField (id) VALUES(33);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'square', 'Anonymous', 34); INSERT INTO dreamField (id) VALUES(34);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'port', 'Anonymous', 35); INSERT INTO dreamField (id) VALUES(35);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'cow', 'Anonymous', 36); INSERT INTO dreamField (id) VALUES(36);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'key', 'Anonymous', 37); INSERT INTO dreamField (id) VALUES(37);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Thomas', 'Anonymous', 38); INSERT INTO dreamField (id) VALUES(38);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Edison', 'Anonymous', 39); INSERT INTO dreamField (id) VALUES(39);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'sub-tropical', 'Anonymous', 40); INSERT INTO dreamField (id) VALUES(40);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'southernmost', 'Anonymous', 41); INSERT INTO dreamField (id) VALUES(41);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'city', 'Anonymous', 42); INSERT INTO dreamField (id) VALUES(42);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'eagle', 'Anonymous', 43); INSERT INTO dreamField (id) VALUES(43);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'dredgers', 'Anonymous', 44); INSERT INTO dreamField (id) VALUES(44);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'key', 'Anonymous', 45); INSERT INTO dreamField (id) VALUES(45);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'sunset', 'Anonymous', 46); INSERT INTO dreamField (id) VALUES(46);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'celebration', 'Anonymous', 47); INSERT INTO dreamField (id) VALUES(47);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'west', 'Anonymous', 48); INSERT INTO dreamField (id) VALUES(48);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'martillo', 'Anonymous', 49); INSERT INTO dreamField (id) VALUES(49);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'treasure', 'Anonymous', 50); INSERT INTO dreamField (id) VALUES(50);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'parrot', 'Anonymous', 51); INSERT INTO dreamField (id) VALUES(51);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'heads', 'Anonymous', 52); INSERT INTO dreamField (id) VALUES(52);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'island', 'Anonymous', 53); INSERT INTO dreamField (id) VALUES(53);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'key', 'Anonymous', 54); INSERT INTO dreamField (id) VALUES(54);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'deer', 'Anonymous', 55); INSERT INTO dreamField (id) VALUES(55);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Ernest', 'Anonymous', 56); INSERT INTO dreamField (id) VALUES(56);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Hemingway', 'Anonymous', 57); INSERT INTO dreamField (id) VALUES(57);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'web', 'Anonymous', 58); INSERT INTO dreamField (id) VALUES(58);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'development', 'Anonymous', 59); INSERT INTO dreamField (id) VALUES(59);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'new', 'Anonymous', 60); INSERT INTO dreamField (id) VALUES(60);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'town', 'Anonymous', 61); INSERT INTO dreamField (id) VALUES(61);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'homeless', 'Anonymous', 62); INSERT INTO dreamField (id) VALUES(62);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'buoy', 'Anonymous', 63); INSERT INTO dreamField (id) VALUES(63);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Matthew', 'Anonymous', 64); INSERT INTO dreamField (id) VALUES(64);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'C.', 'Anonymous', 65); INSERT INTO dreamField (id) VALUES(65);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Perry', 'Anonymous', 66); INSERT INTO dreamField (id) VALUES(66);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'fish', 'Anonymous', 67); INSERT INTO dreamField (id) VALUES(67);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'channel', 'Anonymous', 68); INSERT INTO dreamField (id) VALUES(68);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'simonton', 'Anonymous', 69); INSERT INTO dreamField (id) VALUES(69);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'yellow', 'Anonymous', 70); INSERT INTO dreamField (id) VALUES(70);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'tail', 'Anonymous', 71); INSERT INTO dreamField (id) VALUES(71);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'sun', 'Anonymous', 72); INSERT INTO dreamField (id) VALUES(72);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'tan', 'Anonymous', 73); INSERT INTO dreamField (id) VALUES(73);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'queen', 'Anonymous', 74); INSERT INTO dreamField (id) VALUES(74);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'conch', 'Anonymous', 75); INSERT INTO dreamField (id) VALUES(75);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'ship', 'Anonymous', 76); INSERT INTO dreamField (id) VALUES(76);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'wreck', 'Anonymous', 77); INSERT INTO dreamField (id) VALUES(77);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'power', 'Anonymous', 78); INSERT INTO dreamField (id) VALUES(78);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'boat', 'Anonymous', 79); INSERT INTO dreamField (id) VALUES(79);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'races', 'Anonymous', 80); INSERT INTO dreamField (id) VALUES(80);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'laid', 'Anonymous', 81); INSERT INTO dreamField (id) VALUES(81);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'back', 'Anonymous', 82); INSERT INTO dreamField (id) VALUES(82);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'bight', 'Anonymous', 83); INSERT INTO dreamField (id) VALUES(83);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'coconut', 'Anonymous', 84); INSERT INTO dreamField (id) VALUES(84);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'trees', 'Anonymous', 85); INSERT INTO dreamField (id) VALUES(85);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Lou', 'Anonymous', 86); INSERT INTO dreamField (id) VALUES(86);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Gehrig', 'Anonymous', 87); INSERT INTO dreamField (id) VALUES(87);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'snorkel', 'Anonymous', 88); INSERT INTO dreamField (id) VALUES(88);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'hurricane', 'Anonymous', 89); INSERT INTO dreamField (id) VALUES(89);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'christmas', 'Anonymous', 90); INSERT INTO dreamField (id) VALUES(90);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'tree', 'Anonymous', 91); INSERT INTO dreamField (id) VALUES(91);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'island', 'Anonymous', 92); INSERT INTO dreamField (id) VALUES(92);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'US', 'Anonymous', 93); INSERT INTO dreamField (id) VALUES(93);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, '1', 'Anonymous', 94); INSERT INTO dreamField (id) VALUES(94);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'chickens', 'Anonymous', 95); INSERT INTO dreamField (id) VALUES(95);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'old', 'Anonymous', 96); INSERT INTO dreamField (id) VALUES(96);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'town', 'Anonymous', 97); INSERT INTO dreamField (id) VALUES(97);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'smathers', 'Anonymous', 98); INSERT INTO dreamField (id) VALUES(98);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'beach', 'Anonymous', 99); INSERT INTO dreamField (id) VALUES(99);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'harbor', 'Anonymous', 100); INSERT INTO dreamField (id) VALUES(100);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'dingy', 'Anonymous', 101); INSERT INTO dreamField (id) VALUES(101);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Spanish', 'Anonymous', 102); INSERT INTO dreamField (id) VALUES(102);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'galleon', 'Anonymous', 103); INSERT INTO dreamField (id) VALUES(103);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Santa', 'Anonymous', 104); INSERT INTO dreamField (id) VALUES(104);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Margarita', 'Anonymous', 105); INSERT INTO dreamField (id) VALUES(105);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Key', 'Anonymous', 106); INSERT INTO dreamField (id) VALUES(106);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'West', 'Anonymous', 107); INSERT INTO dreamField (id) VALUES(107);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'ipsum', 'Anonymous', 108); INSERT INTO dreamField (id) VALUES(108);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'wisteria', 'Anonymous', 109); INSERT INTO dreamField (id) VALUES(109);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'island', 'Anonymous', 110); INSERT INTO dreamField (id) VALUES(110);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Whitehead', 'Anonymous', 111); INSERT INTO dreamField (id) VALUES(111);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Street', 'Anonymous', 112); INSERT INTO dreamField (id) VALUES(112);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'little', 'Anonymous', 113); INSERT INTO dreamField (id) VALUES(113);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'white', 'Anonymous', 114); INSERT INTO dreamField (id) VALUES(114);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'house', 'Anonymous', 115); INSERT INTO dreamField (id) VALUES(115);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'eastern', 'Anonymous', 116); INSERT INTO dreamField (id) VALUES(116);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'dry', 'Anonymous', 117); INSERT INTO dreamField (id) VALUES(117);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'rocks', 'Anonymous', 118); INSERT INTO dreamField (id) VALUES(118);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'lobster', 'Anonymous', 119); INSERT INTO dreamField (id) VALUES(119);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'beach', 'Anonymous', 120); INSERT INTO dreamField (id) VALUES(120);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Key', 'Anonymous', 121); INSERT INTO dreamField (id) VALUES(121);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'West', 'Anonymous', 122); INSERT INTO dreamField (id) VALUES(122);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Pink', 'Anonymous', 123); INSERT INTO dreamField (id) VALUES(123);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Shrimp', 'Anonymous', 124); INSERT INTO dreamField (id) VALUES(124);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'conch', 'Anonymous', 125); INSERT INTO dreamField (id) VALUES(125);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'cuban', 'Anonymous', 126); INSERT INTO dreamField (id) VALUES(126);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'chug.', 'Anonymous', 127); INSERT INTO dreamField (id) VALUES(127);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Lorem', 'Anonymous', 128); INSERT INTO dreamField (id) VALUES(128);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'ipsum', 'Anonymous', 129); INSERT INTO dreamField (id) VALUES(129);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Treasure', 'Anonymous', 130); INSERT INTO dreamField (id) VALUES(130);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'port', 'Anonymous', 131); INSERT INTO dreamField (id) VALUES(131);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'mile', 'Anonymous', 132); INSERT INTO dreamField (id) VALUES(132);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'zero', 'Anonymous', 133); INSERT INTO dreamField (id) VALUES(133);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Matthew', 'Anonymous', 134); INSERT INTO dreamField (id) VALUES(134);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'C.', 'Anonymous', 135); INSERT INTO dreamField (id) VALUES(135);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Perry', 'Anonymous', 136); INSERT INTO dreamField (id) VALUES(136);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'bone', 'Anonymous', 137); INSERT INTO dreamField (id) VALUES(137);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'cay', 'Anonymous', 138); INSERT INTO dreamField (id) VALUES(138);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Key', 'Anonymous', 139); INSERT INTO dreamField (id) VALUES(139);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'West', 'Anonymous', 140); INSERT INTO dreamField (id) VALUES(140);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'roosters', 'Anonymous', 141); INSERT INTO dreamField (id) VALUES(141);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'reef', 'Anonymous', 142); INSERT INTO dreamField (id) VALUES(142);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'cow', 'Anonymous', 143); INSERT INTO dreamField (id) VALUES(143);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'key', 'Anonymous', 144); INSERT INTO dreamField (id) VALUES(144);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'higgs', 'Anonymous', 145); INSERT INTO dreamField (id) VALUES(145);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'beach', 'Anonymous', 146); INSERT INTO dreamField (id) VALUES(146);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'christmas', 'Anonymous', 147); INSERT INTO dreamField (id) VALUES(147);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'tree', 'Anonymous', 148); INSERT INTO dreamField (id) VALUES(148);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'island', 'Anonymous', 149); INSERT INTO dreamField (id) VALUES(149);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'schooner', 'Anonymous', 150); INSERT INTO dreamField (id) VALUES(150);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'wharf', 'Anonymous', 151); INSERT INTO dreamField (id) VALUES(151);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'key', 'Anonymous', 152); INSERT INTO dreamField (id) VALUES(152);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'lime', 'Anonymous', 153); INSERT INTO dreamField (id) VALUES(153);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Captain', 'Anonymous', 154); INSERT INTO dreamField (id) VALUES(154);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Eric', 'Anonymous', 155); INSERT INTO dreamField (id) VALUES(155);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'hammock', 'Anonymous', 156); INSERT INTO dreamField (id) VALUES(156);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'cafe', 'Anonymous', 157); INSERT INTO dreamField (id) VALUES(157);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'con', 'Anonymous', 158); INSERT INTO dreamField (id) VALUES(158);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'leche', 'Anonymous', 159); INSERT INTO dreamField (id) VALUES(159);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Fort', 'Anonymous', 160); INSERT INTO dreamField (id) VALUES(160);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Jefferson', 'Anonymous', 161); INSERT INTO dreamField (id) VALUES(161);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'parrot', 'Anonymous', 162); INSERT INTO dreamField (id) VALUES(162);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'heads', 'Anonymous', 163); INSERT INTO dreamField (id) VALUES(163);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Key', 'Anonymous', 164); INSERT INTO dreamField (id) VALUES(164);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'West', 'Anonymous', 165); INSERT INTO dreamField (id) VALUES(165);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'ipsum', 'Anonymous', 166); INSERT INTO dreamField (id) VALUES(166);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'sand', 'Anonymous', 167); INSERT INTO dreamField (id) VALUES(167);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'key', 'Anonymous', 168); INSERT INTO dreamField (id) VALUES(168);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'mangroves', 'Anonymous', 169); INSERT INTO dreamField (id) VALUES(169);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'star', 'Anonymous', 170); INSERT INTO dreamField (id) VALUES(170);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'fish', 'Anonymous', 171); INSERT INTO dreamField (id) VALUES(171);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Fort', 'Anonymous', 172); INSERT INTO dreamField (id) VALUES(172);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Zachary', 'Anonymous', 173); INSERT INTO dreamField (id) VALUES(173);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'coconut', 'Anonymous', 174); INSERT INTO dreamField (id) VALUES(174);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'trees', 'Anonymous', 175); INSERT INTO dreamField (id) VALUES(175);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'new', 'Anonymous', 176); INSERT INTO dreamField (id) VALUES(176);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'town', 'Anonymous', 177); INSERT INTO dreamField (id) VALUES(177);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'tank', 'Anonymous', 178); INSERT INTO dreamField (id) VALUES(178);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'island', 'Anonymous', 179); INSERT INTO dreamField (id) VALUES(179);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'conch', 'Anonymous', 180); INSERT INTO dreamField (id) VALUES(180);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'fritters', 'Anonymous', 181); INSERT INTO dreamField (id) VALUES(181);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'US', 'Anonymous', 182); INSERT INTO dreamField (id) VALUES(182);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, '1', 'Anonymous', 183); INSERT INTO dreamField (id) VALUES(183);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Lou', 'Anonymous', 184); INSERT INTO dreamField (id) VALUES(184);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Gehrig', 'Anonymous', 185); INSERT INTO dreamField (id) VALUES(185);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'mel', 'Anonymous', 186); INSERT INTO dreamField (id) VALUES(186);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'fisher', 'Anonymous', 187); INSERT INTO dreamField (id) VALUES(187);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'stern', 'Anonymous', 188); INSERT INTO dreamField (id) VALUES(188);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'music', 'Anonymous', 189); INSERT INTO dreamField (id) VALUES(189);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'web', 'Anonymous', 190); INSERT INTO dreamField (id) VALUES(190);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'design', 'Anonymous', 191); INSERT INTO dreamField (id) VALUES(191);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'dredgers', 'Anonymous', 192); INSERT INTO dreamField (id) VALUES(192);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'key', 'Anonymous', 193); INSERT INTO dreamField (id) VALUES(193);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'yellow', 'Anonymous', 194); INSERT INTO dreamField (id) VALUES(194);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'tail', 'Anonymous', 195); INSERT INTO dreamField (id) VALUES(195);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'lays', 'Anonymous', 196); INSERT INTO dreamField (id) VALUES(196);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'fishing', 'Anonymous', 197); INSERT INTO dreamField (id) VALUES(197);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'conch', 'Anonymous', 198); INSERT INTO dreamField (id) VALUES(198);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'republic', 'Anonymous', 199); INSERT INTO dreamField (id) VALUES(199);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'sun', 'Anonymous', 200); INSERT INTO dreamField (id) VALUES(200);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'queen', 'Anonymous', 201); INSERT INTO dreamField (id) VALUES(201);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'conch', 'Anonymous', 202); INSERT INTO dreamField (id) VALUES(202);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Laid', 'Anonymous', 203); INSERT INTO dreamField (id) VALUES(203);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Back', 'Anonymous', 204); INSERT INTO dreamField (id) VALUES(204);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Key', 'Anonymous', 205); INSERT INTO dreamField (id) VALUES(205);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'West', 'Anonymous', 206); INSERT INTO dreamField (id) VALUES(206);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'conch', 'Anonymous', 207); INSERT INTO dreamField (id) VALUES(207);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'sunset', 'Anonymous', 208); INSERT INTO dreamField (id) VALUES(208);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'shipwreck', 'Anonymous', 209); INSERT INTO dreamField (id) VALUES(209);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'harbor', 'Anonymous', 210); INSERT INTO dreamField (id) VALUES(210);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'watersports', 'Anonymous', 211); INSERT INTO dreamField (id) VALUES(211);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'bight', 'Anonymous', 212); INSERT INTO dreamField (id) VALUES(212);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'sunset', 'Anonymous', 213); INSERT INTO dreamField (id) VALUES(213);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'key', 'Anonymous', 214); INSERT INTO dreamField (id) VALUES(214);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'buoy', 'Anonymous', 215); INSERT INTO dreamField (id) VALUES(215);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Spanish', 'Anonymous', 216); INSERT INTO dreamField (id) VALUES(216);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'galleon', 'Anonymous', 217); INSERT INTO dreamField (id) VALUES(217);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Santa', 'Anonymous', 218); INSERT INTO dreamField (id) VALUES(218);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'Margarita', 'Anonymous', 219); INSERT INTO dreamField (id) VALUES(219);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'eastern', 'Anonymous', 220); INSERT INTO dreamField (id) VALUES(220);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'dry', 'Anonymous', 221); INSERT INTO dreamField (id) VALUES(221);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'rocks', 'Anonymous', 222); INSERT INTO dreamField (id) VALUES(222);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'palm', 'Anonymous', 223); INSERT INTO dreamField (id) VALUES(223);
INSERT INTO comments (video_id, text, handle, timeStamp) VALUES(0, 'tree', 'Anonymous', 224); INSERT INTO dreamField (id) VALUES(224);
